name: Atualizar Bases CCO

on:
  repository_dispatch:
    types: [atualizar-csv]

permissions:
  contents: write

jobs:
  salvar-dados:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout do Repositório
        uses: actions/checkout@v3

      - name: Decodificar e Salvar o Ficheiro CSV
        run: |
          echo "${{ github.event.client_payload.csv_base64 }}" | base64 --decode > "${{ github.event.client_payload.arquivo }}"

      - name: Enviar Alterações para o Repositório
        run: |
          git config --global user.name "Robo Automacao CCO"
          git config --global user.email "automacao@vli.com"
          git add "${{ github.event.client_payload.arquivo }}"
          git diff --staged --quiet || git commit -m "Atualizacao automatica do ficheiro ${{ github.event.client_payload.arquivo }}"
          git push || echo "Sem alterações para enviar"
